# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # deploy_to_stg:
  #   docker:
  #     - image: circleci/node:10.15
  #   working_directory: ~/repo

  #   steps:
  #     - run:
  #         name: show result of ls cmd
  #         command: ls

  #     - checkout

  #     - run:
  #         name: show result of ls cmd after checkout
  #         command: ls

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run:
      #     name: show current directory
      #     command: pwd

      # - run: npm install
      # - run:
      #     name: 'Install Dependecies'
      #     command: npm install --save-dev firebase-tools

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: 'Build Client Code(gatsby によるビルド実行)'
      #     command: npx gatsby build
      # - run:
      #     name: 'Deploy to Hosting'
      #     command: >- 
      #         npx firebase deploy --only hosting --project "gatsby-blog-5b0ce" --token "1/1n3cOguxPw_alaSuyvba9mIB9D-MpQQz0CVRPFJi8vY"

  deploy_to_stg:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout
      # build
      # test
      - run:
          name: change branch to staging
          command: git checkout staging
      - run:
          name: merge master to staging
          command: git merge master
      - run:
          name: delete current/stg tag
          command: git tag -d current/stg || echo "there's no current/stg tag"
      - run:
          name: add current/stg tag
          command: git tag current/stg
      - run:
          name: delete remote current/stg tag
          command: git push origin :refs/tags/current/stg || echo "there's no current/stg tag"
      - run:
          name: push to staging branch
          command: git push origin -u staging --tags
      # firebase deploy

  deploy_to_production:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout
      # build
      # test
      - run:
          name: checkout staging branch
          command: git checkout $(git rev-list -n 1 current/stg)
      - run:
          name: change branch to production
          command: git checkout production
      - run:
          name: merge staging to production
          command: git merge staging
      - run:
          name: delete current/prod tag
          command: git tag -d current/prod || echo "there's no current/prod tag"
      - run:
          name: add current/prod tag
          command: git tag current/prod
      - run:
          name: delete remote current/prod tag
          command: git push origin :refs/tags/current/prod || echo "there's no current/prod tag"
      - run:
          name: push to production branch
          command: git push origin -u production --tags
      # firebase deploy

  rollback_stg:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout
      # build
      # test
      - run:
          name: checkout staging branch
          command: git checkout $(git rev-list -n 1 current/stg)
      - run:
          name: delete current/stg tag
          command: git tag -d current/stg || echo "there's no current/stg tag"
      - run:
          name: checkout most recent commit
          command: git checkout $(git log --oneline --merges --max-count=1 | awk '{print $1}')
      - run:
          name: add current/stg tag
          command: git tag current/stg
      - run:
          name: delete remote current/stg tag
          command: git push origin :refs/tags/current/stg || echo "there's no current/stg tag"
      - run:
          name: push to staging branch
          command: git push origin --tags
      # firebase deploy

  rollback_prod:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout
      # build
      # test
      - run:
          name: checkout production branch
          command: git checkout $(git rev-list -n 1 current/prod)
      - run:
          name: delete current/prod tag
          command: git tag -d current/prod || echo "there's no current/prod tag"
      - run:
          name: checkout most recent commit
          command: git checkout $(git log --oneline --merges --max-count=1 | awk '{print $1}')
      - run:
          name: add current/prod tag
          command: git tag current/prod
      - run:
          name: delete remote current/prod tag
          command: git push origin :refs/tags/current/prod || echo "there's no current/prod tag"
      - run:
          name: push to production branch
          command: git push origin --tags
      # firebase deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy_to_stg:
          filters:
            branches:
              only: master
